ch:
  addr: clickhouse:9000
  user: default
  password:
  database: uptrace
  max_execution_time: 30s
pg:
  addr: postgres:5432
  user: uptrace
  password: uptrace
  database: uptrace

projects:
  - id: 1
    name: Uptrace
    token: project1_secret_token
    pinned_attrs:
      - service
      - host_name
      - deployment_environment
    group_by_env: false
    group_funcs_by_service: false
    prom_compat: true

  - id: 2
    name: My project
    token: project2_secret_token
    pinned_attrs:
      - service
      - host_name
      - deployment_environment
    group_by_env: false
    group_funcs_by_service: false
    prom_compat: true

auth:
  users:
    - name: Anonymous
      email: uptrace@localhost
      password: uptrace

ch_schema:
  compression: ZSTD(3)
  replicated: false
  spans:
    ttl_delete: 7 DAY
    storage_policy: 'default'
  metrics:
    ttl_delete: 30 DAY
    storage_policy: 'default'

listen:
  grpc:
    addr: ':14317'
  http:
    addr: ':14318'

metrics:
  drop_attrs:
    - telemetry.sdk.language
    - telemetry.sdk.name
    - telemetry.sdk.version
logs:
  level: INFO

secret_key: 102c1a557c314fc28198acd017960843

debug: false
